export const services = [
  {
    id: 1,
    title: "Basic Website",
    description: "Perfect for small businesses and startups",
    features: [
      "3-5 Pages Design",
      "Responsive Design",
      "Contact Form",
      "Basic SEO",
      "1 Month Support",
      "Mobile Friendly",
    ],
    price: "Rs 25,000",
    recommended: false,
    category: "web",
    icon: "🌐",
  },
  {
    id: 2,
    title: "E-Commerce Store",
    description: "Complete online store with payment integration",
    features: [
      "Up to 50 Products",
      "Payment Gateway",
      "Admin Dashboard",
      "Inventory Management",
      "6 Months Support",
      "SSL Certificate",
    ],
    price: "Rs 35,000",
    recommended: true,
    category: "web",
    icon: "🛒",
  },
  {
    id: 3,
    title: "Mobile App",
    description: "Cross-platform mobile application",
    features: [
      "iOS & Android",
      "UI/UX Design",
      "Push Notifications",
      "API Integration",
      "App Store Deployment",
      "1 Year Support",
    ],
    price: "Rs 65,000",
    recommended: false,
    category: "mobile",
    icon: "📱",
  },
  {
    id: 4,
    title: "UI/UX Design",
    description: "Professional interface design",
    features: [
      "Wireframing",
      "Prototyping",
      "User Research",
      "Design System",
      "Responsive Designs",
      "Style Guide",
    ],
    price: "Rs 70,000",
    recommended: false,
    category: "design",
    icon: "🎨",
  },
  {
    id: 5,
    title: "Custom Web App",
    description: "Tailored web application development",
    features: [
      "Custom Features",
      "Database Design",
      "User Authentication",
      "Admin Panel",
      "API Development",
      "1 Year Support",
    ],
    price: "Rs 100,000",
    recommended: false,
    category: "web",
    icon: "💻",
  },
  {
    id: 6,
    title: "Branding Package",
    description: "Complete brand identity",
    features: [
      "Logo Design",
      "Business Cards",
      "Social Media Kit",
      "Brand Guidelines",
      "Stationery Design",
      "3 Revisions",
    ],
    price: "Rs 15,000",
    recommended: false,
    category: "design",
    icon: "✨",
  },
  {
    id: 7,
    title: "SEO Optimization",
    description: "Boost your website's visibility",
    features: [
      "Keyword Research",
      "On-Page SEO",
      "Technical Audit",
      "Backlink Strategy",
      "Monthly Reporting",
      "6 Months Service",
    ],
    price: "Rs 25,000",
    recommended: false,
    category: "other",
    icon: "📈",
  },
  {
    id: 8,
    title: "Maintenance & Support",
    description: "Ongoing technical support",
    features: [
      "24/7 Monitoring",
      "Regular Updates",
      "Security Patches",
      "Backup Management",
      "Performance Tuning",
      "Unlimited Support",
    ],
    price: "Rs 30,000/month",
    recommended: false,
    category: "other",
    icon: "🔧",
  },
];
